# Generated by Django 5.2.17 on 2026-09-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=60, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Árbitro',
                'verbose_name_plural': 'Árbitros',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=60)),
                ('capacidade', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Estádio',
                'verbose_name_plural': 'Estádios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=60, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('sigla', models.CharField(help_text='Código FIFA de três letras, como BRA ou ARG', max_length=3, unique=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selecoes', to='mundial.grupo')),
            ],
            options={
                'verbose_name': 'Seleção',
                'verbose_name_plural': 'Seleções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('GR', 'Fase de grupos'), ('DA', 'Dezesseis avos de final'), ('OI', 'Oitavas de final'), ('QU', 'Quartas de final'), ('SE', 'Semifinal'), ('TE', 'Disputa do terceiro lugar'), ('FI', 'Final')], default='GR', max_length=2, verbose_name='Fase')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
                ('gols_mandante', models.PositiveIntegerField(blank=True, null=True)),
                ('gols_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('registrada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('arbitros', models.ManyToManyField(blank=True, related_name='partidas', to='mundial.arbitro', verbose_name='Árbitros')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='mundial.estadio', verbose_name='Estádio')),
                ('grupo', models.ForeignKey(blank=True, help_text='Preencher apenas para partidas da fase de grupos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='mundial.grupo')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_como_mandante', to='mundial.selecao')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_como_visitante', to='mundial.selecao')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['data_hora'],
            },
        ),
    ]
